### PR TITLE
FIX Multiple timestamp additions

### LINKED ISSUE #335: Timestamp addition for static attributes generate multiple identical timestamp attributes
When a device defines static_attributes, and those attributes are sent to the Context Broker, the Timestamp is also added to the attributes. But when a single device request generates multiple NGSI updateContext, the Timestamp attribute in the metadatas is multiplied times the number of requests. This seems to be a problem with metadata addition in the DB (the same object retrieved once from the database is modified instead of creating a new one, and the timestamp is added instead of modified).

### PR DESCRIPTION
**Pull request by dmoranj**
Fixes #335

### CODE REVIEW

File: lib/services/ngsi/ngsiService.js [hunk 1]
```diff
@@ -184,11 +184,23 @@ function addTimestamp(payload) {
...
         if (!attribute.metadatas) {
             attribute.metadatas = [];
         }
 
-        attribute.metadatas.push(timestamp);
+        for (var i = 0; i < attribute.metadatas.length; i++) {
+            if (attribute.metadatas[i].type === constants.TIMESTAMP_TYPE &&
+                attribute.metadatas[i].name === constants.TIMESTAMP_ATTRIBUTE) {
+                attribute.metadatas[i].value = timestamp.value;
+                timestampFound = true;
```
Comment (gtorodelvalle) [inline lib/services/ngsi/ngsiService.js]: You could `break` the loop to avoid further processing once the `timestamp` metadata entry is found and its value updated :)

**Comment by gtorodelvalle** [comment]
LGTM and merging once Travis is OK with it... ;)
