### PR TITLE
Fix empty `device_id` on device registration

### LINKED ISSUE #1298: Device missing of device_id can be provisioned as usual
### Description:

Device missing of device_id can be provisioned as usual

### Steps to reproduce:

Provision a device using the iotagent-node-lib API "POST @ host:4041/iot/devices"
 
```
{
    "devices": [
        {
            "device_id": "",
            "entity_name": "urn:ngsi-ld:Device:age01_Car",
            "entity_type": "Device",
            "attributes": [
                {
                    "object_id": "ns=3;s=EngineBrake",
                    "name": "EngineBrake",
                    "type": "Number"
                }
             ],
             "lazy": [],
            "commands": [],
            "static_attributes": []
        }
    ]
}
```

### Expected Output:

`{"name":"MISSING_ATTRIBUTES","message":"The request was not well formed:Missing attributes: [\"device_id\"]"}
`
### Actual Output: 

`201 Created`

### Devices GET Output:

```
{
    "count": 1,
    "devices": [
        {
            "device_id": "",
            "service": "openiot5",
            "service_path": "/demo",
            "entity_name": "urn:ngsi-ld:Device:age09_Car",
            "entity_type": "Device",
            "attributes": [
                {
                    "object_id": "ns=3;s=EngineBrake",
                    "name": "EngineBrake",
                    "type": "Number"
                }
            ],
            "lazy": [],
            "commands": [],
            "static_attributes": []
        }
    ]
}

```

### Affected Product Version:

iotagent-node-lib latest

### Environment details (with versions):

OS: Windowd 10
Env (Docker/K8s): Docker
Application: iotagent-opcua

### PR DESCRIPTION
**Pull request by mapedraza**
This PR fix #1298 :

In this part of the code:
https://github.com/telefonicaid/iotagent-node-lib/blob/38ba03bf04c1e38687048eb8dbc2bd0137bc82c8/lib/services/northBound/deviceProvisioningServer.js#L150-L170

The IoTA calls to `checkMandatoryQueryParams()` passing an array of mandatory params in the body (`['device_id']`) and each single device of the request. 

Reviewing `checkMandatoryQueryParams()`
https://github.com/telefonicaid/iotagent-node-lib/blob/38ba03bf04c1e38687048eb8dbc2bd0137bc82c8/lib/services/northBound/restUtils.js#L44-L77

We can see it is only checking if the key exists, but not the value. 

Since `checkMandatoryQueryParams` [is not used in other part in the codebase](https://github.com/telefonicaid/iotagent-node-lib/search?q=%27checkMandatoryQueryParams%27), a simple approach could be to check if not empty or null inside `checkMandatoryQueryParams()` function in case of match

### Solution

This PR checks if elements exists and the value is not empty or null

### CODE REVIEW

File: lib/services/northBound/restUtils.js [hunk 1]
```diff
@@ -53,11 +53,9 @@ function checkMandatoryQueryParams(mandatoryAttributes, body, callback) {
     for (const p in mandatoryAttributes) {
```
Comment (fgalan) [inline lib/services/northBound/restUtils.js:53]: Entry to CNR needed.

Comment (mapedraza) [reply lib/services/northBound/restUtils.js:53]: Done in https://github.com/telefonicaid/iotagent-node-lib/pull/1300/commits/eabcbf0c1f8c305e6b6d2d333254563ebb8f1713

**Review by fgalan — APPROVED** [review]
LGTM
