### PR TITLE
Task/single configuration mode

### LINKED ISSUE #17: Change the Identification of the Devices.
Early in the development of the IoT Agent, the library API was thought to use the combination of deviceId and deviceType as a key to distinguish different devices. This assumption doesn't hold anymore, so it's time to change it.

### LINKED ISSUE #260: Entity retrieval on incoming notifications or queries uses the entity name without the type
When a request comes to the IOTA Northbound interface, the IOTA uses the entity name alone to retrieve the information of the device that generated the entity. This is an error, as multiple entities with the same name but different type may coexist for a single service. The identification should be changed to take this into account.

A similar problem may exist for entities with the same name in different services.

### LINKED ISSUE #263: Initial entity provisioning does not take configurations into account
When a new device is provisioned, its representing entity is created in the Context Broker with initial values, to allow all the updateContext operations to use the UPDATE action type (that requires the presence of the attribute that is going to be modified). In the case where the attributes are defined at Configuration level (not device level), this creation fails, as it uses just the attributes defined in the provisioned device (instead of using the merge of both). Similar problems may be found for different scenarios for the same causes: the multiplicity of sources of definition for the devices configuration. We should think carefully about how to solve this problem as we may solve future bugs if we treat it carefully (maybe moving around an object that is a merge of both the device information and the configuration one, making the former override the latter).

### LINKED ISSUE #343: Change the way the Configurations work
In order to align with the old IoT Agents (maked as a need in production projects), the way Configurations  work must be changed. With the current behavior:
- For each subservice, multiple configurations can be defined. Each one is defined by its type.
- Whenever a device is provisioned, the device is associated to a configuration iff it belongs to the same subservice and has the same type.

With the new behavior, each Configuration will be associated to a single subservice, and the type will be marked optional both for the Configurations and the Devices.

This behavior may be reverted in the future, to reenable multiple configurations per service.

### PR DESCRIPTION
**Pull request by dmoranj**
Fixes #343
Fixes #263
Fixes #260
Fixes #17

This PR changes the way Devices are identified, by using both the Device ID and the (service, subserviceID) instead of supposing a globally unique DeviceID. This has impact in a huge part of the code.

This code comes with a new property in the configuration: `singleConfigurationMode`.

### CODE REVIEW

File: lib/services/devices/deviceRegistryMemory.js [hunk 1]
```diff
@@ -35,26 +35,41 @@ var registeredDevices = {},
...
-    delete registeredDevices[id];
+function removeDevice(id, service, subservice, callback) {
+    var services = Object.keys(registeredDevices);
 
-    logger.debug(context, 'Removing device with id [%s].', id);
+    if (!subservice && !callback) {
+        callback = service;
+    }
+
+    for (var i = 0; i < services.length; i++) {
```
Comment (gtorodelvalle) [inline lib/services/devices/deviceRegistryMemory.js]: This may cause unexpected behaviour in the case where the callback function is passed as the `service` parameter. The `length` property exists for functions and it indicates the number of arguments passed to the function. Consequently, it may only cause these unexpected behaviour in the case when a callback taking arguments is passed.

On the other hand, it seems that if no service is passed, the device is not deleted so maybe what is no longer needed is the code to control the arguments passed in case the `service` and `subservice` are required arguments.

File: lib/services/devices/deviceRegistryMemory.js [hunk 2]
```diff
@@ -110,16 +128,20 @@ function listDevices(service, subservice, limit, offset, callback) {
...
 
-function getDevice(id, callback) {
-    if (registeredDevices[id]) {
-        callback(null, registeredDevices[id]);
+function getDevice(id, service, subservice, callback) {
+    if (!subservice && !callback) {
+        callback = service;
+    }
+
+    if (registeredDevices[service] && registeredDevices[service][id]) {
```
Comment (gtorodelvalle) [inline lib/services/devices/deviceRegistryMemory.js]: I think this may lead to unexpected results in case the callback function is passed as the `service` argument :)

File: lib/services/devices/deviceService.js [hunk 3]
```diff
@@ -205,45 +205,97 @@ function registerDevice(deviceObj, callback) {
...
 
-        if (!deviceData.type) {
-            deviceData.type = config.getConfig().defaultType;
+    function findConfigurationGroup(deviceObj, callback) {
+        function handlerGroupFind(error, group) {
+            if (error || !group) {
+                callback(null, null);
+            } else {
+                callback(null, group);
+            }
```
Comment (gtorodelvalle) [inline lib/services/devices/deviceService.js]: The whole previous `if`clause seems to be "equivalent" to `callback(null, group)` (the only difference being that the second argument of the `callback` will be passed as `undefined` instead as `null`.

File: lib/services/devices/deviceService.js [hunk 4]
```diff
@@ -292,13 +351,13 @@ function unregisterDevice(id, callback) {
...
 
-    config.getRegistry().get(id, function(error, device) {
+    config.getRegistry().get(id, service, subservice, function(error, device) {
         async.waterfall([
             async.apply(removeAllSubscriptions, device),
             processUnsubscribes,
             async.apply(registrationUtils.sendRegistrations, true, device),
             processContextUnregister,
-            async.apply(config.getRegistry().remove, id)
+            async.apply(config.getRegistry().remove, id, service, subservice)
```
Comment (gtorodelvalle) [inline lib/services/devices/deviceService.js]: There are some occurrences of `async.apply` which could directly be substituted by `apply`.

File: test/unit/examples/deviceProvisioningRequests/provisionDuplicatedDev.json [hunk 5]
```diff
@@ -0,0 +1,12 @@
...
+    {
+      "device_id": "Light1",
+      "protocol": "GENERIC_PROTO",
+      "service" : "smartGondor",
+      "service_path": "gardens",
+      "entity_name": "TheFirstLight",
+      "entity_type": "TheLightType"
+    }
+  ]
+}
```
Comment (gtorodelvalle) [inline test/unit/examples/deviceProvisioningRequests/provisionDuplicatedDev.json]: Final blank line appreciated :)

File: test/unit/examples/groupProvisioningRequests/provisionDuplicateGroup.json [hunk 6]
```diff
@@ -0,0 +1,35 @@
...
+      "static_attributes": [
+        {
+          "name": "bootstrapServer",
+          "type": "Address",
+          "value": "127.0.0.1"
+        }
+      ]
+    }
+  ]
+}
```
Comment (gtorodelvalle) [inline test/unit/examples/groupProvisioningRequests/provisionDuplicateGroup.json]: Final blank line appreciated :)

File: test/unit/examples/groupProvisioningRequests/provisionFullGroup.json [hunk 7]
```diff
@@ -0,0 +1,36 @@
...
+      "static_attributes": [
+        {
+          "name": "bootstrapServer",
+          "type": "Address",
+          "value": "127.0.0.1"
+        }
+      ]
+    }
+  ]
+}
```
Comment (gtorodelvalle) [inline test/unit/examples/groupProvisioningRequests/provisionFullGroup.json]: Final blank line appreciated :)

File: lib/services/devices/deviceRegistryMemory.js (hunk 1 above)
Comment (dmoranj) [inline lib/services/devices/deviceRegistryMemory.js]: I don't think so. It seems you are mixing the `service` parameter with the `services` internal variable. Look at line 61: the `services` object is an array, coming from the execution of the `Object.keys()` function. 

Regarding the second objection, in the case no service is passed, the device is removed from all the services.

File: lib/services/devices/deviceRegistryMemory.js (hunk 2 above)
Comment (dmoranj) [inline lib/services/devices/deviceRegistryMemory.js]: You are right... That shouldn't be the case, actually. One of the overall features of this PR is to make the service and subservice used along the full stack, so there shouldn't be any calls without service. I have filed an issue to add checks for all the internal methods, [here](https://github.com/telefonicaid/iotagent-node-lib/issues/349). Requests from the Provisioning API are required to have the fiware-XXX headers.

All that said, I'll remove the guards against service and subservice in the registry methods.

File: lib/services/devices/deviceService.js (hunk 3 above)
Comment (dmoranj) [inline lib/services/devices/deviceService.js]: You're right. Fixed it.

File: lib/services/devices/deviceRegistryMemory.js (hunk 1 above)
Comment (gtorodelvalle) [inline lib/services/devices/deviceRegistryMemory.js]: Ups, my fault, you're completely right... :) PR should not be reviewed beyond 17:00... :D
NTC

File: README.md [hunk 8]
```diff
@@ -14,54 +14,164 @@
...
+
+The following sequence diagram shows the different NGSI interactions an IoT Agent makes with the Context Broker,
+explained in the following subsections (using the example of a OMA Lightweight M2M device).
 
 ![General ](https://raw.github.com/dmoranj/iotagent-node-lib/develop/img/ngsiInteractions.png "NGSI Interactions")
 
-Be aware that the IoT Agents are only required to support NGSI10 operations `updateContext` and `queryContext` in their standard formats (both in XML and JSON) but will not answer to NGSI9 operations (or NGSI convenience operations of any kind).
+Be aware that the IoT Agents are only required to support NGSI10 operations `updateContext` and `queryContext` in their
+standard formats (currently in JSON format; XML deprecated) but will not answer to NGSI9 operations
+(or NGSI convenience operations of any kind).
```
Comment (XavierVal) [inline README.md]: This requirement only apply to IoTAgents, it does not apply to the way CBroker info is requested because CBroker will convert the query/update to the proper NGSI IoTagent needs, isn't it?

File: lib/services/devices/deviceService.js (hunk 4 above)
Comment (dmoranj) [inline lib/services/devices/deviceService.js]: Fixed

File: README.md (hunk 8 above)
Comment (dmoranj) [inline README.md]: Yes, that's the idea. The Context Broker converts all NGSI operations to standard operations when redirecting to Context Providers, to prevent CPs having to implement the full NGSI API.

**Comment by gtorodelvalle** [comment]
LGTM on my side... :)

**Comment by XavierVal** [comment]
LGTM here too 🌴
